version: "3.8"

services:

  db:
    image: postgres
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rest_service_db
      - POSTGRES_PASSWORD=1234

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - db

#  FROM postgres:12-alpine