version: "3.8"

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5300:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rest_service_db
      - POSTGRES_PASSWORD=1234
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/rest_service_db
    depends_on:
      - db

volumes:
  db-data: